### ISSUE TITLE
Total monthly expenses for each category endpoint

### ISSUE THREAD

**Issue by dlarocque** [BarbzCodez/Spendr#103]
- `GET /expenses/total-spending-for-categories`
- params: `startDate`, `endDate`
- Total monthly spending for each category
- Sample response:
`{ categoryTotals: { "GROCERY": 500.0, "TRANSPORT": 200.0, ... } }`

**Comment by DucharmeEthan** [comment]
Closed per https://github.com/BarbzCodez/Spendr/pull/134
